### PR TITLE
Hide REST Client operations

### PR DESCRIPTION
**Pull request by phillip-kruger**
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

### CODE REVIEW

**Review by geoand — APPROVED** [review]

**Comment by geoand** [comment]
Thanks!

**Comment by geoand** [comment]
Actually, are the changes to the properties needed?

**Comment by phillip-kruger** [comment]
The comment out config ? That was just to get the application to work (got that from Clement)

**Comment by phillip-kruger** [comment]
B.t.w, this is just a workaround. This is a bug and I am looking to fix this in SmallRye

**Comment by geoand** [comment]
> The comment out config ? That was just to get the application to work (got that from Clement)

Right, can you revert those and include the actual fix?

**Comment by phillip-kruger** [comment]
Sure. If you say fix, that is the workaround right ? It will take some time to fix this in SmallRye, the TCK has a test for this, so I need to go figure out why this is not working ....

**Comment by phillip-kruger** [comment]
OK check now

**Comment by geoand** [comment]
> Sure. If you say fix, that is the workaround right ? It will take some time to fix this in SmallRye, the TCK has a test for this, so I need to go figure out why this is not working ....

Indeed, I didn't word it properly :)

**Comment by geoand** [comment]
Thanks!

**Pull request merged**
